### ISSUE TITLE
assets:precompile fails

### ISSUE THREAD

**Issue by thunkele** [Crowdtilt/CrowdtiltOpen#130]
```
   Running: rake assets:precompile
   DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/Rakefile:7)
   DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/Rakefile:7)
   rake aborted!
   can't convert nil into String
   (in /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/app/assets/javascripts/ckeditorbase.js.erb)
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/app/assets/javascripts/ckeditorbase.js.erb:4:in `block in singletonclass'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/app/assets/javascripts/ckeditorbase.js.erb:65531:in `instance_eval'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/app/assets/javascripts/ckeditorbase.js.erb:65531:in `singletonclass'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/app/assets/javascripts/ckeditorbase.js.erb:65529:in `__tilt_17735340'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:12:in `initialize'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:105:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:16:in `initialize'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:19:in `block in compile'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/static_compiler.rb:18:in `compile'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:56:in `internal_precompile'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:23:in `invoke_or_reboot_rake_task'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.13/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
   /tmp/build_0081a4d4-2198-4380-92a9-147c57b1f6e6/vendor/bundle/ruby/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
```

**Comment by almereyda** [comment]
@liuhenry But you were right here. I don't want to use AWS, and am currently setting up on Dokku instead of Heroku, but using `ENABLE_ASSET_SYNC=false` definately produces the above error.
